
# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Tietkiemdi            # Site title
name:             TIẾT KIỆM ĐI!          # Your name
avatar:           /theme/img/avatar.jpg   # Path to an avatar image

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
baseurl: "http://tietkiemdi.com"

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages", "_portfolio"]

# Wire in the SASS files in the theme directory.
sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  sass_dir: theme/_sass
  style: compressed

# Turn the projects into a collection.
collections:
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name.html
  portfolio:
    output: true
    title: portfolio
    permalink: /:collection/:name.html

defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: false
      layout: defaults/portfolio
  -
    scope:
      path: "_projects"
    values:
      show_profile: false
      layout: defaults/project
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list




